
##########################################
#     Change these variables !important
##########################################

owner: Dennis Grinch
quote:
  quote: A problem is nothing more than a wrong perspective.
  author: Dennis Grinch

title: Dennis Grinch Blog - Programming tutorials for beginners

include:
  - pages

# Following needed for disqus integration
# Set your 'disqus' account name
disqus: grrinchas

# Uncomment if deployed locally
# url: https://localhost:4000

# Set your host if deployed not locally
# For example "https://yourGitHub.github.io"
url: https://grrinchas.github.io

# Change this to your base URL starting with forward slash if site is in gh-pages branch
# For example /branchName
baseurl:

# Change this to your google analytics ID
google_analytics: UA-78379987-1

# Contact form pupublic key
contact_PK: ef1dcbc3b8a3c2deda24a2efe9a5f65f

##########################################
#          Optional variables
##########################################


# Set maximum posts per page
paginate: 5

# Set permalink
permalink: /:categories/:title

# Set excerpt separator
truncate_size: 30

##########################################
#          Do not change these variables
##########################################

sass:
  sass_dir: _sass


gems: [jekyll-paginate]
paginate_path: /_pages/page:num

