
##########################################
#     Change these variables !important
##########################################

owner: "Name Surname"

title: "Aliquam"

# Set subtitle e.g "blog"
subtitle: "Theme"

# Following needed for disqus integration

# Set your 'disqus' account name
disqus: "..."

# Uncomment if deployed locally
# url: "https://localhost:4000"

# Set your host if deployed not locally
# For example "https://yourGithub.github.io"
# url:

# Change this to your base URL starting with forward slash if site is in gh-pages branch
# For example /branchName
baseurl: ""


##########################################
#          Optional variables
##########################################


# Set maximum posts per page
paginate: 3

# Set permalink
permalink: "/posts/:year/:month/:title"

# Set excerpt separator
truncate_size: 30

##########################################
#          Do not change these variables
##########################################

include:  ["_pages"]
sass:
  sass_dir: _sass


gems: [jekyll-paginate]
paginate_path: "/_pages/page:num"

